name: CI/CD Pipeline for Practice_3

on:
  push:
    paths:
      - 'practice_3/**'
  pull_request:
    paths:
      - 'practice_3/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        working-directory: practice_3
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice_3-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/practice_3-web:latest
