name: Build and Push (Practice 5)

on:
  push:
    paths:
      - 'practice_5/**'
  pull_request:
    paths:
      - 'practice_5/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        working-directory: practice_5
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_IP }}'
          username: '${{ secrets.SERVER_USER }}'
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          port: '${{ secrets.SSH_PORT }}'
          script: |
            cd /home/sergei/ 
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
