name: Build and Push (Practice 5)

on:
  push:
    paths:
      - 'practice_5/**'
  pull_request:
    paths:
      - 'practice_5/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        working-directory: practice_3
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest
  deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull and restart container
          run: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest
            docker stop practice_5-web || true
            docker rm practice_5-web || true
            docker run -d --name practice_5-web -p 81:5004 ${{ secrets.DOCKER_USERNAME }}/practice_5-web:latest
