name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on failure  # 🔹 Уведомление в Telegram
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ Ошибка в $GITHUB_SHA"

      - name: Send Telegram message on success  # 🔹 Уведомление в Telegram
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Успешно прошли проверки $GITHUB_SHA"
